name: Run Scraper

on:
  schedule:
    - cron: '7 7 * * *'  # 4:07 a.m. Brasília time (BRT = UTC-3)
  workflow_dispatch:     # manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: true  # ⬅️ Needed to allow pushing changes

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r scraper/requirements.txt

    - name: Run scraper
      run: python scraper/scraper.py

    - name: Commit and push scraped data
    run: |
    git config user.name github-actions
    git config user.email github-actions@github.com
    git add docs/data/all_data.json
    git commit -m "Update scraped data"
    git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}

