name: Run Scraper

# You will get an error on the automatic updates committing
# if you do not have this line
# You didn't need it before, which is why a lot of yml job files
# you see will not have it (but you need it now!!!)
permissions:
  contents: write

on:
  schedule:
    - cron: '7 7 * * *'  # 4:07 a.m. Brasília time (BRT = UTC-3)
  workflow_dispatch:     # manual trigger

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r scraper/requirements.txt
    - name: Run scraper
      run: python scraper/scraper.py
    - name: Commit and push scraped data
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Check if there are any changes to commit first
        if [ -z "$(git status --porcelain)" ]; then
          echo "No changes to commit."
          exit 0
        fi

        git add docs/data/all_data.json
        git commit -m "Update scraped data"
        
        # Rebase our commit on top of the latest from the remote
        git pull --rebase
        
        git push